apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-tacos.fullname" . }}-backend
  labels:
    {{- include "status-tacos.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "status-tacos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
