---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: status-tacos-database-secret
  namespace: default
spec:
  encryptedData:
    database-password: AgCxUtIGXrTNGsPsuEAzyz5fY8fS8IxTHXqRM/s1rPux/zOpwrvoNXJh7VJiGxg5RO99bfpV9SpkG0woRmTt7m592oxT0vi9lcPvSJufIdqEDDoSHJJi8WX1KaeLk8/ou5G4k3RkLRxznRmkRX2xTgOpRy4HbWBI1z0+Adn6QHpux3FvbWofVZJ0sZrPovX3BdDCq8472Dj1l0tAMistl/jdaiiHeDQlJRuB8Z2/G8Ur6oIL+rVKaD0PBCiTFM5PPUe8fBdV5KaKMtBO6vwZfginK3O3Eq0khttNIUIv9owy4ZDhX5Wexmzj2U+h0h47vaxIXCvEv/MHPYZ3I5vgrIxlD7KAUrvbFVGFpMUmZwI7wt48znRgrCWOcisdihAdZSzDfBLmxsMx2dZnul2VzZpTxmGjziR3ofZFEZPKOrZ2teZS1um7Oq6UVZozKm46faYKQ4c1f4zJINauqVpVZQTf4Rw0upxfw+R4T5aNjbauJqIPzi4a7NZ14m0kNKytEl8pi4RB5OtunlhWWn/6RrFsvDD0l7YYr6zVMLrgGFYLVmkGEiOYmtlW9F5wrgYeirb/zS47VoYwAhFr3dtxDKVCKpG6dTfpHxg1fxe1vw/+LyCGNv8O7298Jmcw/fbxFTAPPQasRvQcVD+9/tHElQDTNyaSqwt/yODGVd5yI/o0lzR/H0SJl80KB1WxpBEFhMKG6hmrOpHfX3EXLioTmyo+ejkjnHav/CRl4ouZqUIgFA==
  template:
    metadata:
      name: status-tacos-database-secret
      namespace: default
    type: Opaque
